package com.foundgine.core.semantic.security.warrants;
public interface ISecurityWarrantDelegationConcurrencyStore {
 SecurityWarrantDelegationConcurrencySnapshot capture(SecurityWarrant parent);
 SecurityWarrantDelegationReservation commitChild(SecurityWarrant parent,SecurityWarrant child,SecurityWarrantDelegationConcurrencySnapshot expected);
 boolean isCommitted(SecurityWarrant child);
}