package com.foundgine.core.semantic.security.warrants;
import java.time.Instant; import java.util.List;
public final class SecurityWarrantExecutionTrust {private SecurityWarrantExecutionTrust(){}
 public static void verify(SecurityWarrant leaf,ISecurityWarrantKeyResolver keys,String expectedIssuer,String expectedAudience,Instant now,List<SecurityWarrant> suppliedChain,ISecurityWarrantDelegationTrustResolver delegationTrust,String tenant){if(leaf==null||keys==null)throw new NullPointerException();if(expectedIssuer==null||expectedIssuer.isBlank())throw new IllegalStateException("Warrant execution requires an explicit trusted issuer.");
  if(leaf.parentId()==null&&leaf.parentDigest()==null&&leaf.delegationPath().isEmpty()){if(suppliedChain!=null&&(suppliedChain.size()!=1||!suppliedChain.get(0).digest().equals(leaf.digest())))throw new IllegalStateException("A root warrant may only be accompanied by itself as the delegation chain.");SecurityWarrantVerifier.verify(leaf,keys,now,expectedIssuer,expectedAudience);return;}
  if(suppliedChain==null||suppliedChain.size()<2)throw new IllegalStateException("Delegated warrant execution requires the complete root-to-leaf delegation chain.");if(!suppliedChain.get(suppliedChain.size()-1).digest().equals(leaf.digest()))throw new IllegalStateException("The supplied delegation chain does not terminate at the executing warrant.");if(delegationTrust==null)throw new IllegalStateException("Delegated warrant execution requires an explicit delegation trust resolver.");SecurityWarrantDelegationChainValidator.validate(suppliedChain,now);SecurityWarrantVerifier.verify(suppliedChain.get(0),keys,now,expectedIssuer,expectedAudience);
  for(int i=1;i<suppliedChain.size();i++){var p=suppliedChain.get(i-1);var c=suppliedChain.get(i);SecurityWarrantVerifier.verify(c,keys,now,p.subject(),expectedAudience);SecurityWarrantDelegationTrust.verifyIssuer(p,c,delegationTrust,now,tenant);if(!c.constraints().isAtMostAsPowerfulAs(p.constraints()))throw new IllegalStateException("Delegation cannot increase warrant authority.");for(var g:c.grants()){boolean ok=p.grants().stream().anyMatch(pg->pg.capability().equals(g.capability())&&pg.operation().equals(g.operation())&&g.resourceScopes().stream().allMatch(scope->pg.resourceScopes().isEmpty()||pg.resourceScopes().contains(scope)));if(!ok)throw new IllegalStateException("Delegation cannot grant capabilities outside the parent warrant.");}}
 }
}
