package com.foundgine.providers.aot.generator;

import com.foundgine.providers.aot.*;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.*;

/**
 * Compile-time metadata generator for Foundgine.
 *
 * <p>The processor intentionally emits ordinary Java source rather than
 * depending on runtime reflection. The generated class is deterministic:
 * declarations are sorted by semantic identity and therefore do not depend
 * on source declaration order.</p>
 */
@SupportedAnnotationTypes("com.foundgine.providers.aot.FoundgineEntity")
@SupportedOptions({"foundgine.generated.package", "foundgine.generated.name"})
public final class FoundgineAotProcessor extends AbstractProcessor {
    private static final String DEFAULT_PACKAGE = "com.foundgine.generated";
    private static final String DEFAULT_NAME = "GeneratedFoundgineMetadata";

    @Override public SourceVersion getSupportedSourceVersion() { return SourceVersion.latestSupported(); }

    @Override public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver() || annotations.isEmpty()) return false;
        List<TypeElement> entities = new ArrayList<>();
        for (Element e : roundEnv.getElementsAnnotatedWith(FoundgineEntity.class)) {
            if (e instanceof TypeElement t) entities.add(t);
        }
        entities.sort(Comparator.comparing(this::entityName).thenComparing(t -> t.getQualifiedName().toString()));
        if (entities.isEmpty()) return false;
        try { generate(entities); }
        catch (IOException ex) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "Foundgine AOT generation failed: " + ex.getMessage());
        }
        return true;
    }

    private void generate(List<TypeElement> entities) throws IOException {
        String pkg = processingEnv.getOptions().getOrDefault("foundgine.generated.package", DEFAULT_PACKAGE);
        String name = processingEnv.getOptions().getOrDefault("foundgine.generated.name", DEFAULT_NAME);
        JavaFileObject file = processingEnv.getFiler().createSourceFile(pkg + "." + name);
        try (Writer w = file.openWriter()) {
            w.write("package " + pkg + ";\n\n");
            w.write("// Generated by FoundgineAotProcessor. DO NOT EDIT.\n");
            w.write("import com.foundgine.core.abstractions.*;\n");
            w.write("import com.foundgine.core.semantic.metadata.*;\n");
            w.write("import java.util.*;\n\n");
            w.write("public final class " + name + " {\n");
            w.write("  private " + name + "() {}\n\n");
            w.write("  public static MetadataRegistry build() {\n    MetadataRegistry registry = new MetadataRegistry();\n");
            for (TypeElement entity : entities) emitEntity(w, entity);
            for (TypeElement entity : entities) emitRelationships(w, entities, entity);
            w.write("    return registry;\n  }\n\n");
            w.write("  public static List<GeneratedEntity> entities() { return List.of(\n");
            for (int i=0;i<entities.size();i++) {
                TypeElement e=entities.get(i);
                if(i>0) w.write(",\n");
                w.write("    new GeneratedEntity(new EntityId("+idLiteral(entityId(e))+"L), \""+escape(entityName(e))+"\", "+e.getQualifiedName()+".class)");
            }
            w.write("\n  ); }\n\n");
            w.write("  public record GeneratedEntity(EntityId id, String name, Class<?> type) {}\n");
            w.write("}\n");
        }
    }

    private void emitEntity(Writer w, TypeElement entity) throws IOException {
        String en = entityName(entity); long eid = entityId(entity);
        List<? extends Element> members = entity.getEnclosedElements();
        List<VariableElement> fields = new ArrayList<>();
        for (Element m : members) {
            if (m.getKind()==ElementKind.FIELD && !m.getModifiers().contains(Modifier.STATIC)) fields.add((VariableElement)m);
        }
        fields.sort(Comparator.comparing((VariableElement f) -> fieldName(f)).thenComparing(f -> f.getSimpleName().toString()));
        FoundgineEntity ann=entity.getAnnotation(FoundgineEntity.class);
        List<String> aliases = aliases(entity);
        String storage = en;
        w.write("    registry.register(new EntityMetadata(new EntityId("+idLiteral(eid)+"L), \""+escape(en)+"\", List.of(\n");
        for(int i=0;i<fields.size();i++) {
            VariableElement f=fields.get(i); FoundgineField a=f.getAnnotation(FoundgineField.class); String fn=fieldName(f); String st=a==null||a.storageName().isBlank()?fn:a.storageName();
            if(i>0) w.write(",\n");
            long fid=a!=null&&a.id()!=0?GeneratorSemanticIdentity.validateExplicitId(a.id(), "field"):fieldId(en,fn); long cid=a!=null&&a.columnId()!=0?a.columnId():GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.columnKey(storage,st));
            String dim=dimension(f); boolean indexed=a!=null&&a.index();
            w.write("      new ColumnMetadata(new ColumnId("+idLiteral(cid)+"L), \""+escape(fn)+"\", \""+escape(st)+"\")");
        }
        w.write("\n    ), \""+escape(storage)+"\", List.of(\n");
        for(int i=0;i<fields.size();i++) {
            VariableElement f=fields.get(i); FoundgineField a=f.getAnnotation(FoundgineField.class); String fn=fieldName(f); String st=a==null||a.storageName().isBlank()?fn:a.storageName();
            if(i>0) w.write(",\n");
            long fid=a!=null&&a.id()!=0?GeneratorSemanticIdentity.validateExplicitId(a.id(), "field"):fieldId(en,fn); long cid=a!=null&&a.columnId()!=0?a.columnId():GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.columnKey(storage,st));
            w.write("      new FieldMetadata(new FieldId("+idLiteral(fid)+"L), \""+escape(fn)+"\", "+typeLiteral(f.asType())+", new ColumnReference(new EntityId("+idLiteral(eid)+"L), new ColumnId("+idLiteral(cid)+"L)), "+stringOrNull(dimension(f))+", "+(a!=null&&a.index())+", "+aliasList(f)+")");
        }
        String pk="null";
        for(VariableElement f:fields) { FoundgineField a=f.getAnnotation(FoundgineField.class); if(a!=null&&a.isPrimaryKey()) {String fn=fieldName(f); String st=a.storageName().isBlank()?fn:a.storageName(); long cid=a!=null&&a.columnId()!=0?a.columnId():GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.columnKey(storage,st)); pk="new ColumnReference(new EntityId("+idLiteral(eid)+"L), new ColumnId("+idLiteral(cid)+"L))"; break;} }
        if(pk.equals("null")) for(VariableElement f:fields) if(f.getSimpleName().contentEquals("id")) {String fn=fieldName(f); String st=fn; long cid=GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.columnKey(storage,st)); pk="new ColumnReference(new EntityId("+idLiteral(eid)+"L), new ColumnId("+idLiteral(cid)+"L))"; break;}
        boolean event=entity.getAnnotation(FoundgineEvent.class)!=null; String temporal="null"; if(event){String tf=entity.getAnnotation(FoundgineEvent.class).occurredAtField(); if(tf.isBlank()&&!fields.isEmpty()) tf="OccurredAt"; for(VariableElement f:fields) if(fieldName(f).equalsIgnoreCase(tf)){String st=f.getSimpleName().toString(); long cid=GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.columnKey(storage,st)); temporal="new ColumnReference(new EntityId("+idLiteral(eid)+"L), new ColumnId("+idLiteral(cid)+"L))";}}
        w.write("\n    ), "+pk+", "+entity.getQualifiedName()+".class, "+event+", "+temporal+", "+aliasList(entity)+"));\n");
    }

    private void emitRelationships(Writer w, List<TypeElement> entities, TypeElement entity) throws IOException {
        String sourceName = entityName(entity);
        long sourceId = entityId(entity);
        for (VariableElement field : declaredFields(entity)) {
            FoundgineRelationship rel = field.getAnnotation(FoundgineRelationship.class);
            if (rel == null) continue;
            TypeElement target = relationshipTarget(field);
            if (target == null) continue;
            String targetName = entityName(target);
            long targetId = entityId(target);
            String relationshipName = rel.name().isBlank() ? field.getSimpleName().toString() : rel.name();
            long rid = rel.id() != 0 ? GeneratorSemanticIdentity.validateExplicitId(rel.id(), "relationship")
                    : GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.relationshipKey(sourceName, relationshipName));
            long sourceColumn = columnId(entity, rel.principalKey());
            long targetColumn = columnId(target, rel.foreignKey());
            w.write("    registry.register(new RelationshipMetadata(new RelationshipId(" + idLiteral(rid) + "L), "
                    + "new EntityId(" + idLiteral(sourceId) + "L), new EntityId(" + idLiteral(targetId) + "L), \""
                    + escape(relationshipName) + "\", new ColumnReference(new EntityId(" + idLiteral(sourceId) + "L), new ColumnId("
                    + idLiteral(sourceColumn) + "L)), new ColumnReference(new EntityId(" + idLiteral(targetId) + "L), new ColumnId("
                    + idLiteral(targetColumn) + "L))));\n");
        }
    }

    private TypeElement relationshipTarget(VariableElement field) {
        for (AnnotationMirror mirror : field.getAnnotationMirrors()) {
            if (!((TypeElement) mirror.getAnnotationType().asElement()).getQualifiedName().contentEquals(FoundgineRelationship.class.getName())) continue;
            for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : mirror.getElementValues().entrySet()) {
                if (!entry.getKey().getSimpleName().contentEquals("target")) continue;
                Object value = entry.getValue().getValue();
                if (value instanceof TypeMirror tm && tm.getKind() == javax.lang.model.type.TypeKind.DECLARED) return (TypeElement) processingEnv.getTypeUtils().asElement(tm);
            }
        }
        return null;
    }

    private List<VariableElement> declaredFields(TypeElement entity) {
        List<VariableElement> fields = new ArrayList<>();
        for (Element m : entity.getEnclosedElements()) {
            if (m.getKind() == ElementKind.FIELD && !m.getModifiers().contains(Modifier.STATIC)) fields.add((VariableElement) m);
        }
        fields.sort(Comparator.comparing((VariableElement f) -> fieldName(f)).thenComparing(f -> f.getSimpleName().toString()));
        return fields;
    }

    private long columnId(TypeElement entity, String fieldName) {
        for (VariableElement field : declaredFields(entity)) {
            if (fieldName(field).equals(fieldName) || field.getSimpleName().contentEquals(fieldName)) {
                FoundgineField a = field.getAnnotation(FoundgineField.class);
                String storage = a == null || a.storageName().isBlank() ? fieldName(field) : a.storageName();
                return a != null && a.columnId() != 0 ? GeneratorSemanticIdentity.validateExplicitId(a.columnId(), "column")
                        : GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.columnKey(entityName(entity), storage));
            }
        }
        throw new IllegalArgumentException("Unknown relationship column '" + fieldName + "' on " + entityName(entity));
    }

    private String aliasList(Element e){ List<String> a=aliases(e); if(a.isEmpty()) return "List.of()"; StringBuilder s=new StringBuilder("List.of("); for(int i=0;i<a.size();i++){if(i>0)s.append(", "); s.append(a.get(i));} return s.append(")").toString(); }
    private List<String> aliases(Element e){ List<String> out=new ArrayList<>(); FoundgineAlias[] aa=e.getAnnotationsByType(FoundgineAlias.class); for(FoundgineAlias a:aa) out.add("new AliasDeclaration(\""+escape(a.value())+"\", "+a.weight()+")"); return out; }
    private String dimension(Element e){ FoundgineSemanticDimension d=e.getAnnotation(FoundgineSemanticDimension.class); return d==null?null:d.value(); }
    private String stringOrNull(String s){return s==null?"null":"\""+escape(s)+"\"";}
    private String typeLiteral(TypeMirror t){return t.toString().replace("java.lang.","")+".class";}
    private String entityName(TypeElement e){FoundgineEntity a=e.getAnnotation(FoundgineEntity.class); return a.name().isBlank()?e.getSimpleName().toString():a.name();}
    private String fieldName(VariableElement f){FoundgineField a=f.getAnnotation(FoundgineField.class); return a==null||a.name().isBlank()?f.getSimpleName().toString():a.name();}
    private long entityId(TypeElement e){FoundgineEntity a=e.getAnnotation(FoundgineEntity.class); return a.id()!=0?a.id():GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.entityKey(entityName(e)));}
    private long fieldId(String en,String fn){return GeneratorSemanticIdentity.hash(GeneratorSemanticIdentity.fieldKey(en,fn));}
    private String idLiteral(long value){return Long.toString(value);}
    private String escape(String s){return s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r");}
}
