using System.ComponentModel;
using System.Text.Json;
using Foundgine.Core.Execution;
using Foundgine.Core.Serialization;
using Foundgine.Core.Semantic.Security.Execution;
using Foundgine.Core.Semantic.Resolution;
using Foundgine.Core.Semantic.Intent;
using Foundgine.Runtime;
using ModelContextProtocol.Server;
using ExecutionContext = Foundgine.Core.Execution.ExecutionContext;

namespace Foundgine.Providers.Tools.MCP;

/// <summary>
/// MCP transport adapter for the Foundgine semantic application contract.
/// MCP arguments are translated into Foundgine inputs; MCP never owns domain
/// semantics, authorization, planning, or provider execution.
/// </summary>
[McpServerToolType]
public sealed class FoundgineMcpTools
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private readonly IFoundgine _foundgine;
    private readonly JsonReadIntentAdapter _adapter;
    private readonly SemanticLexicalReadIntentGrounder? _lexicalGrounder;
    private readonly Func<ExecutionContext> _contextFactory;
    private readonly ISecurityExecutionContextProvider _securityContextProvider;

    /// <param name="foundgine">The Foundgine execution engine.</param>
    /// <param name="adapter">The JSON read-intent adapter. Defaults to a new instance.</param>
    /// <param name="contextFactory">Supplies execution context values per call. Defaults to an empty context.</param>
    /// <param name="securityContextProvider">
    /// Host-owned source of the caller's <see cref="SecurityExecutionContext"/>. Prefer this
    /// over <paramref name="securityContextFactory"/> for new hosts; both may not be supplied
    /// together.
    /// </param>
    /// <param name="securityContextFactory">
    /// Obsolete delegate form of <paramref name="securityContextProvider"/>, retained for
    /// existing hosts. Internally wrapped in a <see cref="DelegateSecurityExecutionContextProvider"/>.
    /// </param>
    /// <param name="lexicalGrounder"></param>
    public FoundgineMcpTools(
        IFoundgine foundgine,
        JsonReadIntentAdapter? adapter = null,
        Func<ExecutionContext>? contextFactory = null,
        ISecurityExecutionContextProvider? securityContextProvider = null,
        Func<SecurityExecutionContext?>? securityContextFactory = null,
        SemanticLexicalReadIntentGrounder? lexicalGrounder = null)
    {
        _foundgine = foundgine ?? throw new ArgumentNullException(nameof(foundgine));
        _adapter = adapter ?? new JsonReadIntentAdapter();
        _lexicalGrounder = lexicalGrounder;
        _contextFactory = contextFactory ?? (() => new ExecutionContext());

        if (securityContextProvider is not null && securityContextFactory is not null)
            throw new ArgumentException(
                $"Only one of {nameof(securityContextProvider)} or {nameof(securityContextFactory)} may be supplied.",
                nameof(securityContextFactory));

        _securityContextProvider = securityContextProvider
                                   ?? (securityContextFactory is not null
                                       ? new DelegateSecurityExecutionContextProvider(securityContextFactory)
                                       : new DelegateSecurityExecutionContextProvider(() => null));
    }

    /// <summary>
    /// Returns the canonical capability contract generated by Foundgine for the
    /// current caller. Discovery does not grant authorization.
    /// </summary>
    [McpServerTool(Name = "foundgine_capabilities")]
    [Description(
        "Discover the Foundgine semantic capability contract available to the current caller. Discovery is descriptive; authorization is re-evaluated during execution.")]
    public string DescribeCapabilities()
    {
        var security = _securityContextProvider.RequireSecurityExecutionContext(
            "MCP", "capability discovery");

        return JsonSerializer.Serialize(
            _foundgine.DescribeCapabilityContract(security),
            JsonOptions);
    }

    /// <summary>
    /// Executes provider-neutral read intent through the Foundgine pipeline.
    /// Authentication, tenant and authorization context remain host-owned.
    /// </summary>
    [McpServerTool(Name = "foundgine_query")]
    [Description(
        "Execute an open Foundgine intent using natural-language lexical grounding. Prefer this tool when the caller has a user-level or natural-language request; Foundgine grounds it against the semantic contract before authorization, planning, and execution. If the intent is already structurally resolved, use foundgine_query_semantic instead. Never supply tenant, identity, authorization predicates, SQL, provider or connection details.")]
    public async Task<string> ExecuteQueryAsync(
        [Description(
            "An open intent: either a natural-language expression (for example, 'show customer orders') or a JSON read intent containing rootEntity, selections, and optional filter/order/limit/offset/after. Authentication and authorization context are host-owned.")]
        string intentJson,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(intentJson))
            throw new ArgumentException("Intent JSON is required.", nameof(intentJson));

        var security = _securityContextProvider.RequireSecurityExecutionContext(
            "MCP", "execution");

        var intent = ParseOpenIntent(intentJson, cancellationToken);
        return await ExecuteResolvedIntentAsync(intent, security, cancellationToken);
    }

    /// <summary>
    /// Executes an already-structured provider-neutral semantic read intent. This is the
    /// explicit structured path for agents that have already resolved the semantic model.
    /// It does not invoke lexical grounding.
    /// </summary>
    [McpServerTool(Name = "foundgine_query_semantic")]
    [Description(
        "Execute an already-structured provider-neutral Foundgine read intent. Use this when the caller already knows the semantic rootEntity, selections, and optional filter/order/pagination. Use foundgine_query for natural-language intent and lexical grounding. Never supply tenant, identity, authorization predicates, SQL, provider or connection details.")]
    public async Task<string> ExecuteSemanticQueryAsync(
        [Description(
            "A provider-neutral JSON read intent containing rootEntity, selections, and optional filter/order/limit/offset/after. The semantic model is public; physical storage details are not.")]
        string intentJson,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(intentJson))
            throw new ArgumentException("Semantic intent JSON is required.", nameof(intentJson));

        var security = _securityContextProvider.RequireSecurityExecutionContext(
            "MCP", "structured execution");

        using var document = JsonDocument.Parse(intentJson);
        if (document.RootElement.ValueKind != JsonValueKind.Object)
            throw new ArgumentException("Structured intent must be a JSON object.", nameof(intentJson));

        var intent = _adapter.Parse(intentJson);
        return await ExecuteResolvedIntentAsync(intent, security, cancellationToken);
    }

    private async Task<string> ExecuteResolvedIntentAsync(
        ReadIntent intent,
        SecurityExecutionContext security,
        CancellationToken cancellationToken)
    {
        intent = intent with { Security = security };
        var result = await _foundgine.ExecuteAsync(
            intent,
            _contextFactory(),
            cancellationToken);

        return JsonSerializer.Serialize(new
        {
            rows = result.Rows.Select(row => row.Values).ToArray(),
            pageInfo = result.PageInfo,
            evidence = result.Evidence,
            receipt = result.Receipt
        }, JsonOptions);
    }

    private ReadIntent ParseOpenIntent(string input, CancellationToken cancellationToken)
    {
        var trimmed = input.Trim();
        if (trimmed.StartsWith("{", StringComparison.Ordinal))
        {
            using var document = JsonDocument.Parse(trimmed);
            if (document.RootElement.TryGetProperty("intent", out var intentProperty) &&
                intentProperty.ValueKind == JsonValueKind.String)
            {
                var expression = intentProperty.GetString();
                if (string.IsNullOrWhiteSpace(expression))
                    throw new ArgumentException("'intent' cannot be empty.", nameof(input));

                return GroundLexically(expression, cancellationToken);
            }

            return _adapter.Parse(trimmed);
        }

        return GroundLexically(trimmed, cancellationToken);
    }

    private ReadIntent GroundLexically(string expression, CancellationToken cancellationToken)
    {
        if (_lexicalGrounder is null)
            throw new InvalidOperationException(
                "Open lexical intents are not configured. Enable Foundgine grounding and register an ISemanticLexicalCandidateSource.");

        return _lexicalGrounder.Ground(expression, cancellationToken);
    }
}