<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.foundgine</groupId><artifactId>foundgine-parent</artifactId><version>${revision}</version></parent><artifactId>foundgine-redteam</artifactId><dependencies><dependency><groupId>com.foundgine</groupId><artifactId>foundgine-core</artifactId><version>${revision}</version></dependency><dependency><groupId>com.foundgine</groupId><artifactId>foundgine-runtime</artifactId><version>${revision}</version></dependency></dependencies></project>
