<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Foundgine.HighAssurance.Banking</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/csharp/Foundgine.Core/Foundgine.Core.csproj" />
    <ProjectReference Include="../../../../src/csharp/Foundgine.Runtime/Foundgine.Runtime.csproj" />
  </ItemGroup>
</Project>