-- Foundgine PostgreSQL E2E initialization.
-- This file is executed by PostgreSQL's docker-entrypoint only when the
-- database cluster is initialized. Tests MUST NOT create/drop schemas/tables.

-- Safety net for Foundgine.Postgres.Vector's E2E tests (PostgresVectorE2ETests),
-- which call CREATE EXTENSION vector themselves via
-- PgVectorSemanticLexiconIndexClient.EnsureSchemaAsync. Creating it here too
-- means the extension is available immediately on a fresh cluster even if a
-- test runs before EnsureSchemaAsync does, and requires the pgvector/pgvector
-- image (a vanilla postgres:17 image cannot satisfy this statement).
CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS fg_mutation;
CREATE SCHEMA IF NOT EXISTS fg_query;
CREATE SCHEMA IF NOT EXISTS fg_stateful;
CREATE SCHEMA IF NOT EXISTS fg_correlation;
CREATE SCHEMA IF NOT EXISTS fg_replay;

-- Mutation graph used by PostgresE2ETests.
CREATE TABLE IF NOT EXISTS fg_mutation."Customer" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Status" text NOT NULL,
    "Notes" text
);
CREATE TABLE IF NOT EXISTS fg_mutation."Profile" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL REFERENCES fg_mutation."Customer"("Id"),
    "Name" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_mutation."Account" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL REFERENCES fg_mutation."Customer"("Id"),
    "Name" text NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "UX_Account_CustomerId" UNIQUE ("CustomerId")
);
CREATE TABLE IF NOT EXISTS fg_mutation."Order" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountId" bigint NOT NULL REFERENCES fg_mutation."Account"("Id"),
    "Status" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_mutation."Payment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" bigint NOT NULL REFERENCES fg_mutation."Order"("Id"),
    "Amount" numeric NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "UX_Payment_OrderId" UNIQUE ("OrderId")
);
CREATE TABLE IF NOT EXISTS fg_mutation."Audit" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL REFERENCES fg_mutation."Customer"("Id"),
    "Kind" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_Profile_CustomerId" ON fg_mutation."Profile"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_Order_AccountId" ON fg_mutation."Order"("AccountId");
CREATE INDEX IF NOT EXISTS "IX_Audit_CustomerId" ON fg_mutation."Audit"("CustomerId");

-- Standalone complex read workload. It intentionally allows multiple accounts
-- per customer, unlike fg_stateful.
CREATE TABLE IF NOT EXISTS fg_query."Customer" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_query."Account" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL REFERENCES fg_query."Customer"("Id"),
    "Balance" numeric NOT NULL,
    "Status" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_query."Transaction" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountId" bigint NOT NULL REFERENCES fg_query."Account"("Id"),
    "Amount" numeric NOT NULL,
    "TransactionDate" timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_Account_CustomerId" ON fg_query."Account"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_Account_Status" ON fg_query."Account"("Status");
CREATE INDEX IF NOT EXISTS "IX_Transaction_AccountId" ON fg_query."Transaction"("AccountId");
CREATE INDEX IF NOT EXISTS "IX_Transaction_Amount" ON fg_query."Transaction"("Amount");

-- Stateful query -> mutation -> query -> mutation proof. Account CustomerId
-- is unique because the mutation graph uses CustomerId as an ON CONFLICT key.
CREATE TABLE IF NOT EXISTS fg_stateful."Customer" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Status" text NOT NULL,
    "Notes" text
);
CREATE TABLE IF NOT EXISTS fg_stateful."Profile" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL REFERENCES fg_stateful."Customer"("Id"),
    "Name" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_stateful."Account" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL REFERENCES fg_stateful."Customer"("Id"),
    "Name" text NOT NULL DEFAULT 'Seed',
    "Status" text NOT NULL,
    "Balance" numeric NOT NULL DEFAULT 150,
    CONSTRAINT "UX_Account_CustomerId" UNIQUE ("CustomerId")
);
CREATE TABLE IF NOT EXISTS fg_stateful."Order" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountId" bigint NOT NULL REFERENCES fg_stateful."Account"("Id"),
    "Status" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_stateful."Payment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" bigint NOT NULL REFERENCES fg_stateful."Order"("Id"),
    "Amount" numeric NOT NULL,
    "Status" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_stateful."Audit" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL REFERENCES fg_stateful."Customer"("Id"),
    "Kind" text NOT NULL
);
CREATE TABLE IF NOT EXISTS fg_stateful."Transaction" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountId" bigint NOT NULL REFERENCES fg_stateful."Account"("Id"),
    "Amount" numeric NOT NULL,
    "TransactionDate" timestamp NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Payment_OrderId" ON fg_stateful."Payment"("OrderId");
CREATE INDEX IF NOT EXISTS "IX_Profile_CustomerId" ON fg_stateful."Profile"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_Order_AccountId" ON fg_stateful."Order"("AccountId");
CREATE INDEX IF NOT EXISTS "IX_Audit_CustomerId" ON fg_stateful."Audit"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_Transaction_AccountId" ON fg_stateful."Transaction"("AccountId");
CREATE INDEX IF NOT EXISTS "IX_Transaction_Amount" ON fg_stateful."Transaction"("Amount");

-- Compiler correlation proof. The rows are created inside test transactions;
-- the schema itself is initialized only here.
CREATE TABLE IF NOT EXISTS fg_correlation."Customer" (
    "Id" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS fg_correlation."Account" (
    "Id" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "CustomerId" bigint NOT NULL,
    "Name" text NOT NULL
);

-- Model-provider replay proof.
CREATE TABLE IF NOT EXISTS fg_replay."Customer" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "TenantId" integer NOT NULL
);

GRANT USAGE ON SCHEMA fg_mutation, fg_query, fg_stateful, fg_correlation, fg_replay TO foundgine;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fg_mutation, fg_query, fg_stateful, fg_correlation, fg_replay TO foundgine;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA fg_mutation, fg_query, fg_stateful, fg_correlation, fg_replay TO foundgine;
