package com.foundgine.providers.storage.sql.retrieval;
import com.foundgine.core.abstractions.*; import com.foundgine.core.semantic.metadata.*; import com.foundgine.core.semantic.resolution.*; import java.sql.*; import java.util.*; import javax.sql.DataSource;
/** PostgreSQL retrieval candidate source. Retrieval is advisory; authorization remains in Core. */
public final class PostgresRetrievalCandidateSource implements IApproximateCandidateSource {
 private final DataSource dataSource; private final IMetadataCatalog metadata; private final PostgresRetrievalOptions options;
 public PostgresRetrievalCandidateSource(DataSource ds,IMetadataCatalog metadata){this(ds,metadata,new PostgresRetrievalOptions());}
 public PostgresRetrievalCandidateSource(DataSource ds,IMetadataCatalog metadata,PostgresRetrievalOptions o){this.dataSource=Objects.requireNonNull(ds);this.metadata=Objects.requireNonNull(metadata);this.options=Objects.requireNonNull(o);}
 @Override public List<RetrievalCandidate> retrieve(SemanticRetrievalRequest r){Objects.requireNonNull(r); EntityMetadata e=metadata.getEntity(r.entityType()); FieldMetadata f=e.effectiveFields().stream().filter(x->x.id().equals(r.field())).findFirst().orElseThrow(); if(f.column()==null) throw new IllegalArgumentException("Retrieval field has no storage mapping: "+f.name()); String table=q(e.effectiveStorageName()), col=q(e.columns().stream().filter(c->c.id().equals(f.column().columnId())).findFirst().orElseThrow().effectiveStorageName()), pk=q(e.columns().stream().filter(c->e.primaryKey()!=null&&c.id().equals(e.primaryKey().columnId())).findFirst().orElseThrow().effectiveStorageName());
  String sql=switch(r.strategy()){case FUZZY -> options.enablePgTrgm()?"SELECT "+pk+", similarity("+col+", ?) score FROM "+table+" WHERE "+col+" % ? ORDER BY score DESC LIMIT ?":null; case FULL_TEXT -> options.enableFullText()?"SELECT "+pk+", ts_rank_cd(to_tsvector(?,COALESCE("+col+"::text,'')),websearch_to_tsquery(?,?)) score FROM "+table+" WHERE to_tsvector(?,COALESCE("+col+"::text,'')) @@ websearch_to_tsquery(?,?) ORDER BY score DESC LIMIT ?":null; case SEARCH -> options.enablePgSearch()?"SELECT "+pk+", 0.0 score FROM "+table+" WHERE "+col+" ||| ? LIMIT ?":null; default -> null;};
  if(sql==null) return List.of(); try(Connection c=dataSource.getConnection(); PreparedStatement p=c.prepareStatement(sql)){int i=1; if(r.strategy()==RetrievalStrategy.FULL_TEXT){p.setString(i++,options.fullTextConfiguration());p.setString(i++,options.fullTextConfiguration());p.setString(i++,r.query());p.setString(i++,options.fullTextConfiguration());p.setString(i++,options.fullTextConfiguration());p.setString(i++,r.query());p.setInt(i++,r.limit());}else{p.setString(i++,r.query());if(r.strategy()==RetrievalStrategy.FUZZY)p.setString(i++,r.query());p.setInt(i++,r.limit());} try(ResultSet rs=p.executeQuery()){List<RetrievalCandidate> out=new ArrayList<>(); CandidateEvidenceKind k=r.strategy()==RetrievalStrategy.FUZZY?CandidateEvidenceKind.TRIGRAM:r.strategy()==RetrievalStrategy.SEARCH?CandidateEvidenceKind.BM25:CandidateEvidenceKind.FULL_TEXT;while(rs.next()){String id=String.valueOf(rs.getObject(1));double score=rs.getDouble(2);out.add(new RetrievalCandidate(r.entityType(),id,score,r.field(),id,List.of(new ResolutionEvidence("PostgreSQL "+r.strategy()+" retrieval",k,score)),k));}return out;}}catch(SQLException ex){throw new IllegalStateException("PostgreSQL retrieval failed",ex);}}
 private static String q(String s){return "\""+s.replace("\"","\"\"")+"\"";}
}
