package com.foundgine.providers.storage.postgresvector;
import com.foundgine.core.abstractions.*; import com.foundgine.core.semantic.resolution.*; import java.sql.*; import java.util.*; import javax.sql.DataSource;
/** pgvector lexical source. Embedding generation is deliberately supplied by the caller. */
public final class PgVectorSemanticLexicalCandidateSource implements ISemanticLexicalCandidateSource {
 public interface EmbeddingGenerator { float[] embed(String token); }
 private final DataSource dataSource; private final EmbeddingGenerator embeddings; private final PgVectorOptions options;
 public PgVectorSemanticLexicalCandidateSource(DataSource ds,EmbeddingGenerator eg,PgVectorOptions o){dataSource=Objects.requireNonNull(ds);embeddings=Objects.requireNonNull(eg);options=Objects.requireNonNull(o);}
 @Override public List<SemanticLexicalCandidate> retrieve(SemanticLexicalRequest r){float[] v=embeddings.embed(r.token());StringBuilder sql=new StringBuilder("SELECT canonical_name,kind,entity_id,relationship_id,field_id,source_entity_id,target_entity_id,value,1-(embedding <=> ?) score FROM ").append(q(options.tableName())).append(" ORDER BY embedding <=> ? LIMIT ?"); try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql.toString())){String vector=Arrays.toString(v);p.setString(1,vector);p.setString(2,vector);p.setInt(3,r.limit());try(ResultSet rs=p.executeQuery()){List<SemanticLexicalCandidate> out=new ArrayList<>();while(rs.next()){SemanticLexicalCandidateKind k=SemanticLexicalCandidateKind.valueOf(rs.getString(2).toUpperCase(Locale.ROOT));double score=rs.getDouble(9);out.add(new SemanticLexicalCandidate(r.token(),k,rs.getString(1),score,id(rs,3),rid(rs,4),fid(rs,5),id(rs,6),id(rs,7),rs.getString(8),List.of(new ResolutionEvidence("pgvector similarity",CandidateEvidenceKind.VECTOR_SIMILARITY,score))));}return out;}}catch(SQLException e){throw new IllegalStateException("pgvector retrieval failed",e);}}
 private static String q(String s){return "\""+s.replace("\"","\"\"")+"\"";} private static EntityId id(ResultSet r,int i)throws SQLException{return r.getObject(i)==null?null:new EntityId(r.getLong(i));} private static RelationshipId rid(ResultSet r,int i)throws SQLException{return r.getObject(i)==null?null:new RelationshipId(r.getLong(i));} private static FieldId fid(ResultSet r,int i)throws SQLException{return r.getObject(i)==null?null:new FieldId(r.getLong(i));}
}
